

version: '3.4'
services:
  php:
    image: jfernancordova/docker-laravel-api-dev:1.0.2
    environment:
      XDEBUG_MODE: 1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8922:8922"
    volumes:
      - .:/muse-laravel-api-dev
